# Assignment: Introduction to Linear Algebra and NumPy
## Objective:
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.

# Working with NumPy
NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

### Task 1:

* Import the `numpy` library and check its version.

In [1]:
import numpy as np
print(np.__version__)

1.26.4


## Creating a NumPy Array:
NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

### Task 2:

* Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
* Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
* Generate an array of 10 evenly spaced values between 0 and 5.

In [3]:
# Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
one_D = np.array([1,2,3,4,5])
one_D

array([1, 2, 3, 4, 5])

In [4]:
one_D.shape

(5,)

In [5]:
one_D.ndim

1

In [14]:
# Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
three_D = np.random.randint(1,9,(3,3,3))
three_D

array([[[8, 7, 8],
        [5, 2, 6],
        [8, 4, 6]],

       [[3, 8, 1],
        [5, 1, 8],
        [2, 2, 7]],

       [[3, 5, 8],
        [6, 2, 2],
        [1, 5, 3]]])

In [15]:
three_D.ndim

3

In [19]:
# Generate an array of 10 evenly spaced values between 0 and 5.
# np.linspace(start, stop, num)
arr = np.linspace(0,5,10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# Indexing and Slicing Arrays:
Indexing and slicing allow you to access and modify specific elements of an array.

### Task 3:

* Access the element in the second row, third column of the 2D array you created above.
* Slice the first two rows and the first two columns from the same array.
* Modify the value in the last row and first column to 100.

In [41]:
# Access the element in the second row, third column of the 2D array you created above.
arr = np.random.randint(0,9,[5,5])
arr


array([[5, 7, 1, 4, 2],
       [3, 2, 7, 2, 8],
       [2, 8, 2, 4, 7],
       [7, 0, 7, 1, 8],
       [1, 5, 0, 0, 4]])

In [42]:
arr.ndim

2

In [43]:
element =arr[1,2]
element

7

In [44]:
# Slice the first two rows and the first two columns from the same array.
arr[:2,:2]

array([[5, 7],
       [3, 2]])

In [47]:
# Modify the value in the last row and first column to 100.
arr[-1,0]=100
arr

array([[  5,   7,   1,   4,   2],
       [  3,   2,   7,   2,   8],
       [  2,   8,   2,   4,   7],
       [  7,   0,   7,   1,   8],
       [100,   5,   0,   0,   4]])

# Properties and Methods of NumPy Arrays
NumPy arrays have several useful properties and methods.

### Task 4:

* Find the shape, size, and data type of the 2D array.
* Change the 1D array into a 2D array of shape (5,1).
* Flatten a multi-dimensional array back into a 1D array.

In [50]:
pm = np.array([[1,2,3],[5,6,7]])
pm

array([[1, 2, 3],
       [5, 6, 7]])

In [55]:
# Find the shape, size, and data type of the 2D array.
print ( pm.shape)
print(pm.size)
print(pm.dtype)

(2, 3)
6
int32


In [56]:
# Change the 1D array into a 2D array of shape (5,1).
one_d = np.array([1,4,5,6,7])
one_d.reshape(5,1)

array([[1],
       [4],
       [5],
       [6],
       [7]])

In [57]:
one_d.shape

(5,)

The .flatten() method in NumPy converts a multi-dimensional array into a 1D array, meaning it collapses all the dimensions into a single dimension, keeping the elements in the same order.

Key Points:
* The method returns a copy of the original array.
* It does not modify the original array.

In [59]:
# Flatten a multi-dimensional array back into a 1D array.
one_d.flatten()
one_d.shape

(5,)

# Operations on NumPy Arrays
Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

### Task 5:

* Add 5 to every element in the 1D array.
* Multiply the 2D array by 3.
* Perform matrix multiplication between the following two arrays:
  
   A = np.array([[1, 2], [3, 4]])
  
   B = np.array([[5, 6], [7, 8]])

In [70]:
# Add 5 to every element in the 1D array.
arr1 = np.array([1,4,5,7,8,9,6])
print(arr1)
add= arr1+5
add

[1 4 5 7 8 9 6]


array([ 6,  9, 10, 12, 13, 14, 11])

In [73]:
# Multiply the 2D array by 3.
arr2 = np.array([[1,4,6,8],[4,8,9,6]])
print(arr2)
multi = arr2 * 3
multi

[[1 4 6 8]
 [4 8 9 6]]


array([[ 3, 12, 18, 24],
       [12, 24, 27, 18]])

In [80]:
# Perform matrix multiplication between the following two arrays:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

multi1 = np.dot(A,B)
multi1



array([[19, 22],
       [43, 50]])

# Understanding Broadcasting
Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

### Task 6:

* Create a 3x3 matrix of ones and a 1D array of length 3.
* Add the 1D array to each row of the matrix using broadcasting.

In [87]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [90]:
result=arr+array
result

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])